Code.require_file "cases/after_connect_test.exs", __DIR__
Code.require_file "cases/backoff_test.exs", __DIR__
Code.require_file "cases/client_test.exs", __DIR__
Code.require_file "cases/close_test.exs", __DIR__
Code.require_file "cases/consumer_test.exs", __DIR__
Code.require_file "cases/continuation_test.exs", __DIR__
Code.require_file "cases/execute_test.exs", __DIR__
Code.require_file "cases/idle_test.exs", __DIR__
Code.require_file "cases/overflow_test.exs", __DIR__
Code.require_file "cases/prepare_execute_test.exs", __DIR__
Code.require_file "cases/prepare_stream_test.exs", __DIR__
Code.require_file "cases/prepare_test.exs", __DIR__
Code.require_file "cases/queue_test.exs", __DIR__
Code.require_file "cases/producer_test.exs", __DIR__
Code.require_file "cases/stream_test.exs", __DIR__
Code.require_file "cases/transaction_execute_test.exs", __DIR__
Code.require_file "cases/transaction_producer_test.exs", __DIR__
Code.require_file "cases/transaction_test.exs", __DIR__
