Code.require_file "cases/after_connect_test.exs", __DIR__
Code.require_file "cases/backoff_test.exs", __DIR__
Code.require_file "cases/client_test.exs", __DIR__
Code.require_file "cases/close_test.exs", __DIR__
Code.require_file "cases/execute_test.exs", __DIR__
Code.require_file "cases/idle_test.exs", __DIR__
Code.require_file "cases/prepare_execute_test.exs", __DIR__
Code.require_file "cases/prepare_test.exs", __DIR__
Code.require_file "cases/proxy_execute_test.exs", __DIR__
Code.require_file "cases/proxy_test.exs", __DIR__
Code.require_file "cases/proxy_transaction_test.exs", __DIR__
Code.require_file "cases/query_test.exs", __DIR__
Code.require_file "cases/queue_test.exs", __DIR__
Code.require_file "cases/transaction_execute_test.exs", __DIR__
Code.require_file "cases/transaction_test.exs", __DIR__
