Code.require_file "cases/backoff_test.exs", __DIR__
Code.require_file "cases/close_test.exs", __DIR__
Code.require_file "cases/execute_test.exs", __DIR__
Code.require_file "cases/idle_test.exs", __DIR__
Code.require_file "cases/prepare_test.exs", __DIR__
Code.require_file "cases/query_test.exs", __DIR__
Code.require_file "cases/run_query_test.exs", __DIR__
Code.require_file "cases/run_transaction_test.exs", __DIR__
Code.require_file "cases/transaction_query_test.exs", __DIR__
Code.require_file "cases/transaction_test.exs", __DIR__
